[build]
  command = "hugo --source exampleSite/ --themesDir .. --theme . -b \"$URL\" --gc --minify"
  publish = "exampleSite/public"

[build.environment]
  HUGO_VERSION = "0.149.0"
  NODE_VERSION = "20"