[build]
  command = "hugo --source exampleSite/ --themesDir .. --theme . -b \"$URL\" --gc --minify"
  publish = "exampleSite/public"

[build.environment]
  HUGO_VERSION = "0.147.8"
  NODE_VERSION = "20"